# Generated by Django 5.1.3 on 2024-11-27 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='Имя пользователя')),
                ('title', models.CharField(max_length=50, verbose_name='Название новости')),
                ('description', models.CharField(max_length=200, verbose_name='Краткое описание новости')),
                ('content', models.TextField(verbose_name='Новость')),
                ('published_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
            ],
        ),
    ]
